add_component: []
remove_component: []
unsupported_components: []
add_k1s_hypervisor: false
static_hostname_ip:
static_hostname_fqdn:
# these parameters are used for multitenants deployment
sf_main_instance: false
sf_tenant_instance: false
