---
- hosts: localhost
  become_method: sudo
  tasks:
    - block:
      - include: tasks/prepare_test_env.yml
      - include: tasks/install_sf_ci_repo.yml
      - include: tasks/yum_update.yml
      - include: tasks/run_sfconfig.yml
      - include: tasks/install_test_env.yml
      always:
      - include: tasks/finish_test.yml
