---
- hosts: localhost
  become_method: sudo
  tasks:
    - block:
      - include_tasks: tasks/prepare_test_env.yml
      - include_tasks: tasks/install_sf_ci_repo.yml
      - include_tasks: tasks/yum_update.yml
      - include_tasks: tasks/run_sfconfig.yml
      - include_tasks: tasks/install_test_env.yml
      always:
      - include_tasks: tasks/finish_test.yml
